"""cria tabela obrigacoes_das

Revision ID: 0fd9bcbb00b8
Revises: 3b45232ee71c
Create Date: 2026-09-03 11:21:27.811405

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fd9bcbb00b8'
down_revision: str | Sequence[str] | None = '3b45232ee71c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obrigacoes_das',
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('paga_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('competencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obrigacoes_das')
    # ### end Alembic commands ###
