"""contas ganham fechamento e vencimento da fatura

Revision ID: 28afd6ffe43b
Revises: 3a4c08ccd5c6
Create Date: 2026-09-05 17:08:24.612879

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28afd6ffe43b'
down_revision: str | Sequence[str] | None = '3a4c08ccd5c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('fechamento', sa.Date(), nullable=True))
    op.add_column('contas', sa.Column('vencimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'vencimento')
    op.drop_column('contas', 'fechamento')
    # ### end Alembic commands ###
