"""categoria da pluggy, pagamento de fatura revisavel, classificacao de recorrencia

Revision ID: 3a4c08ccd5c6
Revises: a79715162ecf
Create Date: 2026-09-04 13:28:32.507264

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a4c08ccd5c6'
down_revision: str | Sequence[str] | None = 'a79715162ecf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentos', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.add_column('movimentos', sa.Column('categoria_id', sa.String(length=20), nullable=True))
    op.add_column('movimentos', sa.Column('pagamento_de_fatura', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_movimentos_categoria_id'), 'movimentos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_movimentos_pagamento_de_fatura'), 'movimentos', ['pagamento_de_fatura'], unique=False)
    op.add_column('recorrencias', sa.Column('apelido', sa.String(length=100), nullable=True))
    op.add_column('recorrencias', sa.Column('categoria', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_recorrencias_categoria'), 'recorrencias', ['categoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recorrencias_categoria'), table_name='recorrencias')
    op.drop_column('recorrencias', 'categoria')
    op.drop_column('recorrencias', 'apelido')
    op.drop_index(op.f('ix_movimentos_pagamento_de_fatura'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_categoria_id'), table_name='movimentos')
    op.drop_column('movimentos', 'pagamento_de_fatura')
    op.drop_column('movimentos', 'categoria_id')
    op.drop_column('movimentos', 'categoria')
    # ### end Alembic commands ###
