"""cria tabela movimentos

Revision ID: 3b45232ee71c
Revises: 
Create Date: 2026-09-03 10:15:23.000951

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b45232ee71c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titularidade', sa.String(length=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('proveniencia', sa.String(length=30), nullable=False),
    sa.Column('identificador_externo', sa.String(length=200), nullable=True),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('duplicado_possivel', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', 'identificador_externo', name='uq_movimentos_fingerprint_id')
    )
    op.create_index(op.f('ix_movimentos_fingerprint'), 'movimentos', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentos_fingerprint'), table_name='movimentos')
    op.drop_table('movimentos')
    # ### end Alembic commands ###
