"""contas ganham bandeira e final, indice em movimentos.data

Revision ID: 79267946be9a
Revises: f8a96fc3a182
Create Date: 2026-09-03 14:47:51.929891

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '79267946be9a'
down_revision: str | Sequence[str] | None = 'f8a96fc3a182'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('bandeira', sa.String(length=30), nullable=True))
    op.add_column('contas', sa.Column('final', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_movimentos_data'), 'movimentos', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentos_data'), table_name='movimentos')
    op.drop_column('contas', 'final')
    op.drop_column('contas', 'bandeira')
    # ### end Alembic commands ###
