"""contas ganham apelido editavel

Revision ID: a1bbbe4eab1d
Revises: 28afd6ffe43b
Create Date: 2026-09-09 20:36:18.997863

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1bbbe4eab1d'
down_revision: str | Sequence[str] | None = '28afd6ffe43b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('apelido', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'apelido')
    # ### end Alembic commands ###
