"""recorrencias detectadas e compromissos futuros

Revision ID: a79715162ecf
Revises: 79267946be9a
Create Date: 2026-09-04 09:44:46.979512

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a79715162ecf'
down_revision: str | Sequence[str] | None = '79267946be9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compromissos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('periodicidade', sa.String(length=20), nullable=False),
    sa.Column('conta_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compromissos_conta_id'), 'compromissos', ['conta_id'], unique=False)
    op.create_index(op.f('ix_compromissos_status'), 'compromissos', ['status'], unique=False)
    op.create_table('recorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_medio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ocorrencias', sa.Integer(), nullable=False),
    sa.Column('primeira_data', sa.Date(), nullable=False),
    sa.Column('ultima_data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_id', 'descricao', name='uq_recorrencias_conta_descricao')
    )
    op.create_index(op.f('ix_recorrencias_conta_id'), 'recorrencias', ['conta_id'], unique=False)
    op.create_index(op.f('ix_recorrencias_status'), 'recorrencias', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recorrencias_status'), table_name='recorrencias')
    op.drop_index(op.f('ix_recorrencias_conta_id'), table_name='recorrencias')
    op.drop_table('recorrencias')
    op.drop_index(op.f('ix_compromissos_status'), table_name='compromissos')
    op.drop_index(op.f('ix_compromissos_conta_id'), table_name='compromissos')
    op.drop_table('compromissos')
    # ### end Alembic commands ###
