"""contas dinamicas: cria contas, movimentos usa conta_id, remove obrigacoes_das

Revision ID: f8a96fc3a182
Revises: 0fd9bcbb00b8
Create Date: 2026-09-03 12:08:31.173570

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8a96fc3a182'
down_revision: str | Sequence[str] | None = '0fd9bcbb00b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limite', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('disponivel', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('obrigacoes_das')
    op.add_column('movimentos', sa.Column('conta_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_movimentos_conta_id'), 'movimentos', ['conta_id'], unique=False)
    op.create_foreign_key(None, 'movimentos', 'contas', ['conta_id'], ['id'])
    op.drop_column('movimentos', 'titularidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentos', sa.Column('titularidade', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movimentos', type_='foreignkey')
    op.drop_index(op.f('ix_movimentos_conta_id'), table_name='movimentos')
    op.drop_column('movimentos', 'conta_id')
    op.create_table('obrigacoes_das',
    sa.Column('competencia', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('paga_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('competencia', name=op.f('obrigacoes_das_pkey'))
    )
    op.drop_table('contas')
    # ### end Alembic commands ###
